//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.03 at 03:53:58 PM TRT 
//


package com.kodat.of.melasoft.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kodat.of.melasoft.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kodat.of.melasoft.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Faktura }
     * 
     */
    public Faktura createFaktura() {
        return new Faktura();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna1 }
     * 
     */
    public TOsobaNiefizycznaPelna1 createTOsobaNiefizycznaPelna1() {
        return new TOsobaNiefizycznaPelna1();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna }
     * 
     */
    public TOsobaFizycznaPelna createTOsobaFizycznaPelna() {
        return new TOsobaFizycznaPelna();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny }
     * 
     */
    public TPodmiotDowolnyPelny createTPodmiotDowolnyPelny() {
        return new TPodmiotDowolnyPelny();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny1 }
     * 
     */
    public TPodmiotDowolny1 createTPodmiotDowolny1() {
        return new TPodmiotDowolny1();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny1 }
     * 
     */
    public TPodmiotDowolnyPelny1 createTPodmiotDowolnyPelny1() {
        return new TPodmiotDowolnyPelny1();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny2 }
     * 
     */
    public TPodmiotDowolny2 createTPodmiotDowolny2() {
        return new TPodmiotDowolny2();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna }
     * 
     */
    public TOsobaFizyczna createTOsobaFizyczna() {
        return new TOsobaFizyczna();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna }
     * 
     */
    public TOsobaNiefizycznaPelna createTOsobaNiefizycznaPelna() {
        return new TOsobaNiefizycznaPelna();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna2 }
     * 
     */
    public TOsobaFizyczna2 createTOsobaFizyczna2() {
        return new TOsobaFizyczna2();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna3 }
     * 
     */
    public TOsobaFizyczna3 createTOsobaFizyczna3() {
        return new TOsobaFizyczna3();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna4 }
     * 
     */
    public TOsobaFizyczna4 createTOsobaFizyczna4() {
        return new TOsobaFizyczna4();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna5 }
     * 
     */
    public TOsobaFizyczna5 createTOsobaFizyczna5() {
        return new TOsobaFizyczna5();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna }
     * 
     */
    public TOsobaNiefizyczna createTOsobaNiefizyczna() {
        return new TOsobaNiefizyczna();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna1 }
     * 
     */
    public TOsobaFizyczna1 createTOsobaFizyczna1() {
        return new TOsobaFizyczna1();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna1 }
     * 
     */
    public TOsobaFizycznaPelna1 createTOsobaFizycznaPelna1() {
        return new TOsobaFizycznaPelna1();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna2 }
     * 
     */
    public TOsobaNiefizyczna2 createTOsobaNiefizyczna2() {
        return new TOsobaNiefizyczna2();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna1 }
     * 
     */
    public TOsobaNiefizyczna1 createTOsobaNiefizyczna1() {
        return new TOsobaNiefizyczna1();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny }
     * 
     */
    public TPodmiotDowolny createTPodmiotDowolny() {
        return new TPodmiotDowolny();
    }

    /**
     * Create an instance of {@link Faktura.Stopka }
     * 
     */
    public Faktura.Stopka createFakturaStopka() {
        return new Faktura.Stopka();
    }

    /**
     * Create an instance of {@link Faktura.Fa }
     * 
     */
    public Faktura.Fa createFakturaFa() {
        return new Faktura.Fa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Zamowienie }
     * 
     */
    public Faktura.Fa.Zamowienie createFakturaFaZamowienie() {
        return new Faktura.Fa.Zamowienie();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji createFakturaFaWarunkiTransakcji() {
        return new Faktura.Fa.WarunkiTransakcji();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji.Transport }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji.Transport createFakturaFaWarunkiTransakcjiTransport() {
        return new Faktura.Fa.WarunkiTransakcji.Transport();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc }
     * 
     */
    public Faktura.Fa.Platnosc createFakturaFaPlatnosc() {
        return new Faktura.Fa.Platnosc();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Rozliczenie }
     * 
     */
    public Faktura.Fa.Rozliczenie createFakturaFaRozliczenie() {
        return new Faktura.Fa.Rozliczenie();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje }
     * 
     */
    public Faktura.Fa.Adnotacje createFakturaFaAdnotacje() {
        return new Faktura.Fa.Adnotacje();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje.NoweSrodkiTransportu }
     * 
     */
    public Faktura.Fa.Adnotacje.NoweSrodkiTransportu createFakturaFaAdnotacjeNoweSrodkiTransportu() {
        return new Faktura.Fa.Adnotacje.NoweSrodkiTransportu();
    }

    /**
     * Create an instance of {@link Faktura.PodmiotUpowazniony }
     * 
     */
    public Faktura.PodmiotUpowazniony createFakturaPodmiotUpowazniony() {
        return new Faktura.PodmiotUpowazniony();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot3 }
     * 
     */
    public Faktura.Podmiot3 createFakturaPodmiot3() {
        return new Faktura.Podmiot3();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot2 }
     * 
     */
    public Faktura.Podmiot2 createFakturaPodmiot2() {
        return new Faktura.Podmiot2();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot1 }
     * 
     */
    public Faktura.Podmiot1 createFakturaPodmiot1() {
        return new Faktura.Podmiot1();
    }

    /**
     * Create an instance of {@link TNaglowek }
     * 
     */
    public TNaglowek createTNaglowek() {
        return new TNaglowek();
    }

    /**
     * Create an instance of {@link TRachunekBankowy }
     * 
     */
    public TRachunekBankowy createTRachunekBankowy() {
        return new TRachunekBankowy();
    }

    /**
     * Create an instance of {@link TPodmiot2 }
     * 
     */
    public TPodmiot2 createTPodmiot2() {
        return new TPodmiot2();
    }

    /**
     * Create an instance of {@link TPodmiot3 }
     * 
     */
    public TPodmiot3 createTPodmiot3() {
        return new TPodmiot3();
    }

    /**
     * Create an instance of {@link TKluczWartosc }
     * 
     */
    public TKluczWartosc createTKluczWartosc() {
        return new TKluczWartosc();
    }

    /**
     * Create an instance of {@link TPodmiot1 }
     * 
     */
    public TPodmiot1 createTPodmiot1() {
        return new TPodmiot1();
    }

    /**
     * Create an instance of {@link TAdres }
     * 
     */
    public TAdres createTAdres() {
        return new TAdres();
    }

    /**
     * Create an instance of {@link TAdres1 }
     * 
     */
    public TAdres1 createTAdres1() {
        return new TAdres1();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej1 }
     * 
     */
    public TIdentyfikatorOsobyFizycznej1 createTIdentyfikatorOsobyFizycznej1() {
        return new TIdentyfikatorOsobyFizycznej1();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej2 }
     * 
     */
    public TIdentyfikatorOsobyFizycznej2 createTIdentyfikatorOsobyFizycznej2() {
        return new TIdentyfikatorOsobyFizycznej2();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznejPelny }
     * 
     */
    public TIdentyfikatorOsobyFizycznejPelny createTIdentyfikatorOsobyFizycznejPelny() {
        return new TIdentyfikatorOsobyFizycznejPelny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznej }
     * 
     */
    public TIdentyfikatorOsobyFizycznej createTIdentyfikatorOsobyFizycznej() {
        return new TIdentyfikatorOsobyFizycznej();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznejZagranicznej }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznejZagranicznej createTIdentyfikatorOsobyNiefizycznejZagranicznej() {
        return new TIdentyfikatorOsobyNiefizycznejZagranicznej();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznej1 }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznej1 createTIdentyfikatorOsobyNiefizycznej1() {
        return new TIdentyfikatorOsobyNiefizycznej1();
    }

    /**
     * Create an instance of {@link TAdres2 }
     * 
     */
    public TAdres2 createTAdres2() {
        return new TAdres2();
    }

    /**
     * Create an instance of {@link TAdresPolski }
     * 
     */
    public TAdresPolski createTAdresPolski() {
        return new TAdresPolski();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu }
     * 
     */
    public TPodmiotDowolnyBezAdresu createTPodmiotDowolnyBezAdresu() {
        return new TPodmiotDowolnyBezAdresu();
    }

    /**
     * Create an instance of {@link TAdresZagraniczny }
     * 
     */
    public TAdresZagraniczny createTAdresZagraniczny() {
        return new TAdresZagraniczny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznej }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznej createTIdentyfikatorOsobyNiefizycznej() {
        return new TIdentyfikatorOsobyNiefizycznej();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu2 }
     * 
     */
    public TPodmiotDowolnyBezAdresu2 createTPodmiotDowolnyBezAdresu2() {
        return new TPodmiotDowolnyBezAdresu2();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu1 }
     * 
     */
    public TPodmiotDowolnyBezAdresu1 createTPodmiotDowolnyBezAdresu1() {
        return new TPodmiotDowolnyBezAdresu1();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyBezAdresu3 }
     * 
     */
    public TPodmiotDowolnyBezAdresu3 createTPodmiotDowolnyBezAdresu3() {
        return new TPodmiotDowolnyBezAdresu3();
    }

    /**
     * Create an instance of {@link TAdresPolski1 }
     * 
     */
    public TAdresPolski1 createTAdresPolski1() {
        return new TAdresPolski1();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyNiefizycznejPelny }
     * 
     */
    public TIdentyfikatorOsobyNiefizycznejPelny createTIdentyfikatorOsobyNiefizycznejPelny() {
        return new TIdentyfikatorOsobyNiefizycznejPelny();
    }

    /**
     * Create an instance of {@link TIdentyfikatorOsobyFizycznejZagranicznej }
     * 
     */
    public TIdentyfikatorOsobyFizycznejZagranicznej createTIdentyfikatorOsobyFizycznejZagranicznej() {
        return new TIdentyfikatorOsobyFizycznejZagranicznej();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna1 .AdresSiedziby }
     * 
     */
    public TOsobaNiefizycznaPelna1 .AdresSiedziby createTOsobaNiefizycznaPelna1AdresSiedziby() {
        return new TOsobaNiefizycznaPelna1 .AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna.AdresZamieszkania }
     * 
     */
    public TOsobaFizycznaPelna.AdresZamieszkania createTOsobaFizycznaPelnaAdresZamieszkania() {
        return new TOsobaFizycznaPelna.AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby createTPodmiotDowolnyPelnyAdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolnyPelny.AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny1 .AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolny1 .AdresZamieszkaniaSiedziby createTPodmiotDowolny1AdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolny1 .AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TPodmiotDowolnyPelny1 .AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolnyPelny1 .AdresZamieszkaniaSiedziby createTPodmiotDowolnyPelny1AdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolnyPelny1 .AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny2 .AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolny2 .AdresZamieszkaniaSiedziby createTPodmiotDowolny2AdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolny2 .AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna.AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna.AdresZamieszkania createTOsobaFizycznaAdresZamieszkania() {
        return new TOsobaFizyczna.AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaNiefizycznaPelna.AdresSiedziby }
     * 
     */
    public TOsobaNiefizycznaPelna.AdresSiedziby createTOsobaNiefizycznaPelnaAdresSiedziby() {
        return new TOsobaNiefizycznaPelna.AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna2 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna2 .AdresZamieszkania createTOsobaFizyczna2AdresZamieszkania() {
        return new TOsobaFizyczna2 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna3 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna3 .AdresZamieszkania createTOsobaFizyczna3AdresZamieszkania() {
        return new TOsobaFizyczna3 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna4 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna4 .AdresZamieszkania createTOsobaFizyczna4AdresZamieszkania() {
        return new TOsobaFizyczna4 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna5 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna5 .AdresZamieszkania createTOsobaFizyczna5AdresZamieszkania() {
        return new TOsobaFizyczna5 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna.AdresSiedziby }
     * 
     */
    public TOsobaNiefizyczna.AdresSiedziby createTOsobaNiefizycznaAdresSiedziby() {
        return new TOsobaNiefizyczna.AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaFizyczna1 .AdresZamieszkania }
     * 
     */
    public TOsobaFizyczna1 .AdresZamieszkania createTOsobaFizyczna1AdresZamieszkania() {
        return new TOsobaFizyczna1 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaFizycznaPelna1 .AdresZamieszkania }
     * 
     */
    public TOsobaFizycznaPelna1 .AdresZamieszkania createTOsobaFizycznaPelna1AdresZamieszkania() {
        return new TOsobaFizycznaPelna1 .AdresZamieszkania();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna2 .AdresSiedziby }
     * 
     */
    public TOsobaNiefizyczna2 .AdresSiedziby createTOsobaNiefizyczna2AdresSiedziby() {
        return new TOsobaNiefizyczna2 .AdresSiedziby();
    }

    /**
     * Create an instance of {@link TOsobaNiefizyczna1 .AdresSiedziby }
     * 
     */
    public TOsobaNiefizyczna1 .AdresSiedziby createTOsobaNiefizyczna1AdresSiedziby() {
        return new TOsobaNiefizyczna1 .AdresSiedziby();
    }

    /**
     * Create an instance of {@link TPodmiotDowolny.AdresZamieszkaniaSiedziby }
     * 
     */
    public TPodmiotDowolny.AdresZamieszkaniaSiedziby createTPodmiotDowolnyAdresZamieszkaniaSiedziby() {
        return new TPodmiotDowolny.AdresZamieszkaniaSiedziby();
    }

    /**
     * Create an instance of {@link Faktura.Stopka.Informacje }
     * 
     */
    public Faktura.Stopka.Informacje createFakturaStopkaInformacje() {
        return new Faktura.Stopka.Informacje();
    }

    /**
     * Create an instance of {@link Faktura.Stopka.Rejestry }
     * 
     */
    public Faktura.Stopka.Rejestry createFakturaStopkaRejestry() {
        return new Faktura.Stopka.Rejestry();
    }

    /**
     * Create an instance of {@link Faktura.Fa.OkresFa }
     * 
     */
    public Faktura.Fa.OkresFa createFakturaFaOkresFa() {
        return new Faktura.Fa.OkresFa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.DaneFaKorygowanej }
     * 
     */
    public Faktura.Fa.DaneFaKorygowanej createFakturaFaDaneFaKorygowanej() {
        return new Faktura.Fa.DaneFaKorygowanej();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Podmiot1K }
     * 
     */
    public Faktura.Fa.Podmiot1K createFakturaFaPodmiot1K() {
        return new Faktura.Fa.Podmiot1K();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Podmiot2K }
     * 
     */
    public Faktura.Fa.Podmiot2K createFakturaFaPodmiot2K() {
        return new Faktura.Fa.Podmiot2K();
    }

    /**
     * Create an instance of {@link Faktura.Fa.ZaliczkaCzesciowa }
     * 
     */
    public Faktura.Fa.ZaliczkaCzesciowa createFakturaFaZaliczkaCzesciowa() {
        return new Faktura.Fa.ZaliczkaCzesciowa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.FakturaZaliczkowa }
     * 
     */
    public Faktura.Fa.FakturaZaliczkowa createFakturaFaFakturaZaliczkowa() {
        return new Faktura.Fa.FakturaZaliczkowa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.FaWiersz }
     * 
     */
    public Faktura.Fa.FaWiersz createFakturaFaFaWiersz() {
        return new Faktura.Fa.FaWiersz();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Zamowienie.ZamowienieWiersz }
     * 
     */
    public Faktura.Fa.Zamowienie.ZamowienieWiersz createFakturaFaZamowienieZamowienieWiersz() {
        return new Faktura.Fa.Zamowienie.ZamowienieWiersz();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji.Umowy }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji.Umowy createFakturaFaWarunkiTransakcjiUmowy() {
        return new Faktura.Fa.WarunkiTransakcji.Umowy();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji.Zamowienia }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji.Zamowienia createFakturaFaWarunkiTransakcjiZamowienia() {
        return new Faktura.Fa.WarunkiTransakcji.Zamowienia();
    }

    /**
     * Create an instance of {@link Faktura.Fa.WarunkiTransakcji.Transport.Przewoznik }
     * 
     */
    public Faktura.Fa.WarunkiTransakcji.Transport.Przewoznik createFakturaFaWarunkiTransakcjiTransportPrzewoznik() {
        return new Faktura.Fa.WarunkiTransakcji.Transport.Przewoznik();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc.ZaplataCzesciowa }
     * 
     */
    public Faktura.Fa.Platnosc.ZaplataCzesciowa createFakturaFaPlatnoscZaplataCzesciowa() {
        return new Faktura.Fa.Platnosc.ZaplataCzesciowa();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc.TerminPlatnosci }
     * 
     */
    public Faktura.Fa.Platnosc.TerminPlatnosci createFakturaFaPlatnoscTerminPlatnosci() {
        return new Faktura.Fa.Platnosc.TerminPlatnosci();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Platnosc.Skonto }
     * 
     */
    public Faktura.Fa.Platnosc.Skonto createFakturaFaPlatnoscSkonto() {
        return new Faktura.Fa.Platnosc.Skonto();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Rozliczenie.Obciazenia }
     * 
     */
    public Faktura.Fa.Rozliczenie.Obciazenia createFakturaFaRozliczenieObciazenia() {
        return new Faktura.Fa.Rozliczenie.Obciazenia();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Rozliczenie.Odliczenia }
     * 
     */
    public Faktura.Fa.Rozliczenie.Odliczenia createFakturaFaRozliczenieOdliczenia() {
        return new Faktura.Fa.Rozliczenie.Odliczenia();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje.Zwolnienie }
     * 
     */
    public Faktura.Fa.Adnotacje.Zwolnienie createFakturaFaAdnotacjeZwolnienie() {
        return new Faktura.Fa.Adnotacje.Zwolnienie();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje.PMarzy }
     * 
     */
    public Faktura.Fa.Adnotacje.PMarzy createFakturaFaAdnotacjePMarzy() {
        return new Faktura.Fa.Adnotacje.PMarzy();
    }

    /**
     * Create an instance of {@link Faktura.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu }
     * 
     */
    public Faktura.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu createFakturaFaAdnotacjeNoweSrodkiTransportuNowySrodekTransportu() {
        return new Faktura.Fa.Adnotacje.NoweSrodkiTransportu.NowySrodekTransportu();
    }

    /**
     * Create an instance of {@link Faktura.PodmiotUpowazniony.DaneKontaktowe }
     * 
     */
    public Faktura.PodmiotUpowazniony.DaneKontaktowe createFakturaPodmiotUpowaznionyDaneKontaktowe() {
        return new Faktura.PodmiotUpowazniony.DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot3 .DaneKontaktowe }
     * 
     */
    public Faktura.Podmiot3 .DaneKontaktowe createFakturaPodmiot3DaneKontaktowe() {
        return new Faktura.Podmiot3 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot2 .DaneKontaktowe }
     * 
     */
    public Faktura.Podmiot2 .DaneKontaktowe createFakturaPodmiot2DaneKontaktowe() {
        return new Faktura.Podmiot2 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot1 .AdresKoresp }
     * 
     */
    public Faktura.Podmiot1 .AdresKoresp createFakturaPodmiot1AdresKoresp() {
        return new Faktura.Podmiot1 .AdresKoresp();
    }

    /**
     * Create an instance of {@link Faktura.Podmiot1 .DaneKontaktowe }
     * 
     */
    public Faktura.Podmiot1 .DaneKontaktowe createFakturaPodmiot1DaneKontaktowe() {
        return new Faktura.Podmiot1 .DaneKontaktowe();
    }

    /**
     * Create an instance of {@link TNaglowek.KodFormularza }
     * 
     */
    public TNaglowek.KodFormularza createTNaglowekKodFormularza() {
        return new TNaglowek.KodFormularza();
    }

}
