//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.03 at 03:53:58 PM TRT 
//


package com.kodat.of.melasoft.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TKodWaluty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TKodWaluty">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="AED"/>
 *     &lt;enumeration value="AFN"/>
 *     &lt;enumeration value="ALL"/>
 *     &lt;enumeration value="AMD"/>
 *     &lt;enumeration value="ANG"/>
 *     &lt;enumeration value="AOA"/>
 *     &lt;enumeration value="ARS"/>
 *     &lt;enumeration value="AUD"/>
 *     &lt;enumeration value="AWG"/>
 *     &lt;enumeration value="AZN"/>
 *     &lt;enumeration value="BAM"/>
 *     &lt;enumeration value="BBD"/>
 *     &lt;enumeration value="BDT"/>
 *     &lt;enumeration value="BGN"/>
 *     &lt;enumeration value="BHD"/>
 *     &lt;enumeration value="BIF"/>
 *     &lt;enumeration value="BMD"/>
 *     &lt;enumeration value="BND"/>
 *     &lt;enumeration value="BOB"/>
 *     &lt;enumeration value="BOV"/>
 *     &lt;enumeration value="BRL"/>
 *     &lt;enumeration value="BSD"/>
 *     &lt;enumeration value="BTN"/>
 *     &lt;enumeration value="BWP"/>
 *     &lt;enumeration value="BYN"/>
 *     &lt;enumeration value="BZD"/>
 *     &lt;enumeration value="CAD"/>
 *     &lt;enumeration value="CDF"/>
 *     &lt;enumeration value="CHE"/>
 *     &lt;enumeration value="CHF"/>
 *     &lt;enumeration value="CHW"/>
 *     &lt;enumeration value="CLF"/>
 *     &lt;enumeration value="CLP"/>
 *     &lt;enumeration value="CNY"/>
 *     &lt;enumeration value="COP"/>
 *     &lt;enumeration value="COU"/>
 *     &lt;enumeration value="CRC"/>
 *     &lt;enumeration value="CUC"/>
 *     &lt;enumeration value="CUP"/>
 *     &lt;enumeration value="CVE"/>
 *     &lt;enumeration value="CZK"/>
 *     &lt;enumeration value="DJF"/>
 *     &lt;enumeration value="DKK"/>
 *     &lt;enumeration value="DOP"/>
 *     &lt;enumeration value="DZD"/>
 *     &lt;enumeration value="EGP"/>
 *     &lt;enumeration value="ERN"/>
 *     &lt;enumeration value="ETB"/>
 *     &lt;enumeration value="EUR"/>
 *     &lt;enumeration value="FJD"/>
 *     &lt;enumeration value="FKP"/>
 *     &lt;enumeration value="GBP"/>
 *     &lt;enumeration value="GEL"/>
 *     &lt;enumeration value="GGP"/>
 *     &lt;enumeration value="GHS"/>
 *     &lt;enumeration value="GIP"/>
 *     &lt;enumeration value="GMD"/>
 *     &lt;enumeration value="GNF"/>
 *     &lt;enumeration value="GTQ"/>
 *     &lt;enumeration value="GYD"/>
 *     &lt;enumeration value="HKD"/>
 *     &lt;enumeration value="HNL"/>
 *     &lt;enumeration value="HRK"/>
 *     &lt;enumeration value="HTG"/>
 *     &lt;enumeration value="HUF"/>
 *     &lt;enumeration value="IDR"/>
 *     &lt;enumeration value="ILS"/>
 *     &lt;enumeration value="IMP"/>
 *     &lt;enumeration value="INR"/>
 *     &lt;enumeration value="IQD"/>
 *     &lt;enumeration value="IRR"/>
 *     &lt;enumeration value="ISK"/>
 *     &lt;enumeration value="JEP"/>
 *     &lt;enumeration value="JMD"/>
 *     &lt;enumeration value="JOD"/>
 *     &lt;enumeration value="JPY"/>
 *     &lt;enumeration value="KES"/>
 *     &lt;enumeration value="KGS"/>
 *     &lt;enumeration value="KHR"/>
 *     &lt;enumeration value="KMF"/>
 *     &lt;enumeration value="KPW"/>
 *     &lt;enumeration value="KRW"/>
 *     &lt;enumeration value="KWD"/>
 *     &lt;enumeration value="KYD"/>
 *     &lt;enumeration value="KZT"/>
 *     &lt;enumeration value="LAK"/>
 *     &lt;enumeration value="LBP"/>
 *     &lt;enumeration value="LKR"/>
 *     &lt;enumeration value="LRD"/>
 *     &lt;enumeration value="LSL"/>
 *     &lt;enumeration value="LYD"/>
 *     &lt;enumeration value="MAD"/>
 *     &lt;enumeration value="MDL"/>
 *     &lt;enumeration value="MGA"/>
 *     &lt;enumeration value="MKD"/>
 *     &lt;enumeration value="MMK"/>
 *     &lt;enumeration value="MNT"/>
 *     &lt;enumeration value="MOP"/>
 *     &lt;enumeration value="MRU"/>
 *     &lt;enumeration value="MUR"/>
 *     &lt;enumeration value="MVR"/>
 *     &lt;enumeration value="MWK"/>
 *     &lt;enumeration value="MXN"/>
 *     &lt;enumeration value="MXV"/>
 *     &lt;enumeration value="MYR"/>
 *     &lt;enumeration value="MZN"/>
 *     &lt;enumeration value="NAD"/>
 *     &lt;enumeration value="NGN"/>
 *     &lt;enumeration value="NIO"/>
 *     &lt;enumeration value="NOK"/>
 *     &lt;enumeration value="NPR"/>
 *     &lt;enumeration value="NZD"/>
 *     &lt;enumeration value="OMR"/>
 *     &lt;enumeration value="PAB"/>
 *     &lt;enumeration value="PEN"/>
 *     &lt;enumeration value="PGK"/>
 *     &lt;enumeration value="PHP"/>
 *     &lt;enumeration value="PKR"/>
 *     &lt;enumeration value="PLN"/>
 *     &lt;enumeration value="PYG"/>
 *     &lt;enumeration value="QAR"/>
 *     &lt;enumeration value="RON"/>
 *     &lt;enumeration value="RSD"/>
 *     &lt;enumeration value="RUB"/>
 *     &lt;enumeration value="RWF"/>
 *     &lt;enumeration value="SAR"/>
 *     &lt;enumeration value="SBD"/>
 *     &lt;enumeration value="SCR"/>
 *     &lt;enumeration value="SDG"/>
 *     &lt;enumeration value="SEK"/>
 *     &lt;enumeration value="SGD"/>
 *     &lt;enumeration value="SHP"/>
 *     &lt;enumeration value="SLL"/>
 *     &lt;enumeration value="SOS"/>
 *     &lt;enumeration value="SRD"/>
 *     &lt;enumeration value="SSP"/>
 *     &lt;enumeration value="STN"/>
 *     &lt;enumeration value="SVC"/>
 *     &lt;enumeration value="SYP"/>
 *     &lt;enumeration value="SZL"/>
 *     &lt;enumeration value="THB"/>
 *     &lt;enumeration value="TJS"/>
 *     &lt;enumeration value="TMT"/>
 *     &lt;enumeration value="TND"/>
 *     &lt;enumeration value="TOP"/>
 *     &lt;enumeration value="TRY"/>
 *     &lt;enumeration value="TTD"/>
 *     &lt;enumeration value="TWD"/>
 *     &lt;enumeration value="TZS"/>
 *     &lt;enumeration value="UAH"/>
 *     &lt;enumeration value="UGX"/>
 *     &lt;enumeration value="USD"/>
 *     &lt;enumeration value="USN"/>
 *     &lt;enumeration value="UYI"/>
 *     &lt;enumeration value="UYU"/>
 *     &lt;enumeration value="UYW"/>
 *     &lt;enumeration value="UZS"/>
 *     &lt;enumeration value="VES"/>
 *     &lt;enumeration value="VND"/>
 *     &lt;enumeration value="VUV"/>
 *     &lt;enumeration value="WST"/>
 *     &lt;enumeration value="XAF"/>
 *     &lt;enumeration value="XAG"/>
 *     &lt;enumeration value="XAU"/>
 *     &lt;enumeration value="XBA"/>
 *     &lt;enumeration value="XBB"/>
 *     &lt;enumeration value="XBC"/>
 *     &lt;enumeration value="XBD"/>
 *     &lt;enumeration value="XCD"/>
 *     &lt;enumeration value="XDR"/>
 *     &lt;enumeration value="XOF"/>
 *     &lt;enumeration value="XPD"/>
 *     &lt;enumeration value="XPF"/>
 *     &lt;enumeration value="XPT"/>
 *     &lt;enumeration value="XSU"/>
 *     &lt;enumeration value="XUA"/>
 *     &lt;enumeration value="XXX"/>
 *     &lt;enumeration value="YER"/>
 *     &lt;enumeration value="ZAR"/>
 *     &lt;enumeration value="ZMW"/>
 *     &lt;enumeration value="ZWL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TKodWaluty", namespace = "http://crd.gov.pl/wzor/2023/06/29/12648/")
@XmlEnum
public enum TKodWaluty {


    /**
     * DIRHAM ZEA
     * 
     */
    AED,

    /**
     * AFGANI
     * 
     */
    AFN,

    /**
     * LEK
     * 
     */
    ALL,

    /**
     * DRAM
     * 
     */
    AMD,

    /**
     * GULDEN ANTYLI HOLENDERSKICH
     * 
     */
    ANG,

    /**
     * KWANZA
     * 
     */
    AOA,

    /**
     * PESO ARGENTYŃSKIE
     * 
     */
    ARS,

    /**
     * DOLAR AUSTRALIJSKI
     * 
     */
    AUD,

    /**
     * GULDEN ARUBAŃSKI
     * 
     */
    AWG,

    /**
     * MANAT AZERBEJDŻAŃSKI
     * 
     */
    AZN,

    /**
     * MARKA ZAMIENNA
     * 
     */
    BAM,

    /**
     * DOLAR BARBADOSKI
     * 
     */
    BBD,

    /**
     * TAKA
     * 
     */
    BDT,

    /**
     * LEW
     * 
     */
    BGN,

    /**
     * DINAR BAHRAJSKI
     * 
     */
    BHD,

    /**
     * FRANK BURUNDYJSKI
     * 
     */
    BIF,

    /**
     * DOLAR BERMUDZKI
     * 
     */
    BMD,

    /**
     * DOLAR BRUNEJSKI
     * 
     */
    BND,

    /**
     * BOLIWIANO
     * 
     */
    BOB,

    /**
     * BOLIWIANO MVDOL
     * 
     */
    BOV,

    /**
     * REAL
     * 
     */
    BRL,

    /**
     * DOLAR BAHAMSKI
     * 
     */
    BSD,

    /**
     * NGULTRUM
     * 
     */
    BTN,

    /**
     * PULA
     * 
     */
    BWP,

    /**
     * RUBEL BIAŁORUSKI
     * 
     */
    BYN,

    /**
     * DOLAR BELIZEŃSKI
     * 
     */
    BZD,

    /**
     * DOLAR KANADYJSKI
     * 
     */
    CAD,

    /**
     * FRANK KONGIJSKI
     * 
     */
    CDF,

    /**
     * FRANK SZWAJCARSKI VIR EURO
     * 
     */
    CHE,

    /**
     * FRANK SZWAJCARSKI
     * 
     */
    CHF,

    /**
     * FRANK SZWAJCARSKI VIR FRANK
     * 
     */
    CHW,

    /**
     * JEDNOSTKA ROZLICZENIOWA CHILIJSKA
     * 
     */
    CLF,

    /**
     * PESO CHILIJSKIE
     * 
     */
    CLP,

    /**
     * YUAN RENMINBI
     * 
     */
    CNY,

    /**
     * PESO KOLUMBIJSKIE
     * 
     */
    COP,

    /**
     * UNIDAD DE VALOR REAL KOLUMBILSKIE
     * 
     */
    COU,

    /**
     * COLON KOSTARYKAŃSKI
     * 
     */
    CRC,

    /**
     * PESO WYMIENIALNE
     * 
     */
    CUC,

    /**
     * PESO KUBAŃSKIE
     * 
     */
    CUP,

    /**
     * ESCUDO REPUBLIKI ZIELONEGO PRZYLĄDKA
     * 
     */
    CVE,

    /**
     * KORONA CZESKA
     * 
     */
    CZK,

    /**
     * FRANK DŻIBUTI
     * 
     */
    DJF,

    /**
     * KORONA DUŃSKA
     * 
     */
    DKK,

    /**
     * PESO DOMINIKAŃSKIE
     * 
     */
    DOP,

    /**
     * DINAR ALGIERSKI
     * 
     */
    DZD,

    /**
     * FUNT EGIPSKI
     * 
     */
    EGP,

    /**
     * NAKFA
     * 
     */
    ERN,

    /**
     * BIRR
     * 
     */
    ETB,

    /**
     * EURO
     * 
     */
    EUR,

    /**
     * DOLAR FIDŻI
     * 
     */
    FJD,

    /**
     * FUNT FALKLANDZKI
     * 
     */
    FKP,

    /**
     * FUNT SZTERLING
     * 
     */
    GBP,

    /**
     * LARI
     * 
     */
    GEL,

    /**
     * FUNT GUERNSEY
     * 
     */
    GGP,

    /**
     * GHANA CEDI
     * 
     */
    GHS,

    /**
     * FUNT GIBRALTARSKI
     * 
     */
    GIP,

    /**
     * DALASI
     * 
     */
    GMD,

    /**
     * FRANK GWINEJSKI
     * 
     */
    GNF,

    /**
     * QUETZAL
     * 
     */
    GTQ,

    /**
     * DOLAR GUJAŃSKI
     * 
     */
    GYD,

    /**
     * DOLAR HONGKONGU
     * 
     */
    HKD,

    /**
     * LEMPIRA
     * 
     */
    HNL,

    /**
     * KUNA
     * 
     */
    HRK,

    /**
     * GOURDE
     * 
     */
    HTG,

    /**
     * FORINT
     * 
     */
    HUF,

    /**
     * RUPIA INDONEZYJSKA
     * 
     */
    IDR,

    /**
     * SZEKEL
     * 
     */
    ILS,

    /**
     * FUNT MANX
     * 
     */
    IMP,

    /**
     * RUPIA INDYJSKA
     * 
     */
    INR,

    /**
     * DINAR IRACKI
     * 
     */
    IQD,

    /**
     * RIAL IRAŃSKI
     * 
     */
    IRR,

    /**
     * KORONA ISLANDZKA
     * 
     */
    ISK,

    /**
     * FUNT JERSEY
     * 
     */
    JEP,

    /**
     * DOLAR JAMAJSKI
     * 
     */
    JMD,

    /**
     * DINAR JORDAŃSKI
     * 
     */
    JOD,

    /**
     * JEN
     * 
     */
    JPY,

    /**
     * SZYLING KENIJSKI
     * 
     */
    KES,

    /**
     * SOM
     * 
     */
    KGS,

    /**
     * RIEL
     * 
     */
    KHR,

    /**
     * FRANK KOMORÓW
     * 
     */
    KMF,

    /**
     * WON PÓŁNOCNO­KOREAŃSKI
     * 
     */
    KPW,

    /**
     * WON POŁUDNIOWO­KOREAŃSKI
     * 
     */
    KRW,

    /**
     * DINAR KUWEJCKI
     * 
     */
    KWD,

    /**
     * DOLAR KAJMAŃSKI
     * 
     */
    KYD,

    /**
     * TENGE
     * 
     */
    KZT,

    /**
     * KIP
     * 
     */
    LAK,

    /**
     * FUNT LIBAŃSKI
     * 
     */
    LBP,

    /**
     * RUPIA LANKIJSKA
     * 
     */
    LKR,

    /**
     * DOLAR LIBERYJSKI
     * 
     */
    LRD,

    /**
     * LOTI
     * 
     */
    LSL,

    /**
     * DINAR LIBIJSKI
     * 
     */
    LYD,

    /**
     * DIRHAM MAROKAŃSKI
     * 
     */
    MAD,

    /**
     * LEJ MOŁDAWII
     * 
     */
    MDL,

    /**
     * ARIARY
     * 
     */
    MGA,

    /**
     * DENAR
     * 
     */
    MKD,

    /**
     * KYAT
     * 
     */
    MMK,

    /**
     * TUGRIK
     * 
     */
    MNT,

    /**
     * PATACA
     * 
     */
    MOP,

    /**
     * OUGUIYA
     * 
     */
    MRU,

    /**
     * RUPIA MAURITIUSU
     * 
     */
    MUR,

    /**
     * RUPIA MALEDIWSKA
     * 
     */
    MVR,

    /**
     * KWACHA MALAWIJSKA
     * 
     */
    MWK,

    /**
     * PESO MEKSYKAŃSKIE
     * 
     */
    MXN,

    /**
     * UNIDAD DE INVERSION (UDI) MEKSYKAŃSKIE
     * 
     */
    MXV,

    /**
     * RINGGIT
     * 
     */
    MYR,

    /**
     * METICAL
     * 
     */
    MZN,

    /**
     * DOLAR NAMIBIJSKI
     * 
     */
    NAD,

    /**
     * NAIRA
     * 
     */
    NGN,

    /**
     * CORDOBA ORO
     * 
     */
    NIO,

    /**
     * KORONA NORWESKA
     * 
     */
    NOK,

    /**
     * RUPIA NEPALSKA
     * 
     */
    NPR,

    /**
     * DOLAR NOWOZELANDZKI
     * 
     */
    NZD,

    /**
     * RIAL OMAŃSKI
     * 
     */
    OMR,

    /**
     * BALBOA
     * 
     */
    PAB,

    /**
     * SOL
     * 
     */
    PEN,

    /**
     * KINA
     * 
     */
    PGK,

    /**
     * PESO FILIPIŃSKIE
     * 
     */
    PHP,

    /**
     * RUPIA PAKISTAŃSKA
     * 
     */
    PKR,

    /**
     * ZŁOTY
     * 
     */
    PLN,

    /**
     * GUARANI
     * 
     */
    PYG,

    /**
     * RIAL KATARSKI
     * 
     */
    QAR,

    /**
     * LEJ RUMUŃSKI
     * 
     */
    RON,

    /**
     * DINAR SERBSKI
     * 
     */
    RSD,

    /**
     * RUBEL ROSYJSKI
     * 
     */
    RUB,

    /**
     * FRANK RWANDYJSKI
     * 
     */
    RWF,

    /**
     * RIAL SAUDYJSKI
     * 
     */
    SAR,

    /**
     * DOLAR WYSP SALOMONA
     * 
     */
    SBD,

    /**
     * RUPIA SESZELSKA
     * 
     */
    SCR,

    /**
     * FUNT SUDAŃSKI
     * 
     */
    SDG,

    /**
     * KORONA SZWEDZKA
     * 
     */
    SEK,

    /**
     * DOLAR SINGAPURSKI
     * 
     */
    SGD,

    /**
     * FUNT ŚWIĘTEJ HELENY (ŚWIĘTA HELENA I WYSPA WNIEBOWSTĄPIENIA)
     * 
     */
    SHP,

    /**
     * LEONE
     * 
     */
    SLL,

    /**
     * SZYLING SOMALIJSKI
     * 
     */
    SOS,

    /**
     * DOLAR SURINAMSKI
     * 
     */
    SRD,

    /**
     * FUNT POŁUDNIOWOSUDAŃSKI
     * 
     */
    SSP,

    /**
     * DOBRA
     * 
     */
    STN,

    /**
     * COLON SALWADORSKI (SV1)
     * 
     */
    SVC,

    /**
     * FUNT SYRYJSKI
     * 
     */
    SYP,

    /**
     * LILANGENI
     * 
     */
    SZL,

    /**
     * BAT
     * 
     */
    THB,

    /**
     * SOMONI
     * 
     */
    TJS,

    /**
     * MANAT TURKMEŃSKI
     * 
     */
    TMT,

    /**
     * DINAR TUNEZYJSKI
     * 
     */
    TND,

    /**
     * PAANGA
     * 
     */
    TOP,

    /**
     * LIRA TURECKA
     * 
     */
    TRY,

    /**
     * DOLAR TRYNIDADU I TOBAGO
     * 
     */
    TTD,

    /**
     * NOWY DOLAR TAJWAŃSKI
     * 
     */
    TWD,

    /**
     * SZYLING TANZAŃSKI
     * 
     */
    TZS,

    /**
     * HRYWNA
     * 
     */
    UAH,

    /**
     * SZYLING UGANDYJSKI
     * 
     */
    UGX,

    /**
     * DOLAR AMERYKAŃSKI
     * 
     */
    USD,

    /**
     * DOLAR AMERYKAŃSKI (NEXT DAY)
     * 
     */
    USN,

    /**
     * PESO EN UNIDADES INDEXADAS URUGWAJSKIE
     * 
     */
    UYI,

    /**
     * PESO URUGWAJSKIE
     * 
     */
    UYU,

    /**
     * PESO EN UNIDADES INDEXADAS URUGWAJSKIE
     * 
     */
    UYW,

    /**
     * SUM
     * 
     */
    UZS,

    /**
     * BOLIWAR SOBERANO 
     * 
     */
    VES,

    /**
     * DONG
     * 
     */
    VND,

    /**
     * VATU
     * 
     */
    VUV,

    /**
     * TALA
     * 
     */
    WST,

    /**
     * FRANK CFA (BEAC)
     * 
     */
    XAF,

    /**
     * SREBRO
     * 
     */
    XAG,

    /**
     * ZŁOTO
     * 
     */
    XAU,

    /**
     * BOND MARKETS UNIT EUROPEAN COMPOSITE UNIT (EURCO)
     * 
     */
    XBA,

    /**
     * BOND MARKETS UNIT EUROPEAN MONETARY UNIT (E.M.U.-6)
     * 
     */
    XBB,

    /**
     * BOND MARKETS UNIT EUROPEAN UNIT OF ACCOUNT 9 (E.U.A.-9)
     * 
     */
    XBC,

    /**
     * BOND MARKETS UNIT EUROPEAN UNIT OF ACCOUNT 17 (E.U.A.-17)
     * 
     */
    XBD,

    /**
     * DOLAR WSCHODNIO­KARAIBSKI
     * 
     */
    XCD,

    /**
     * SDR MIĘDZYNARODOWY FUNDUSZ WALUTOWY
     * 
     */
    XDR,

    /**
     * FRANK CFA (BCEAO)
     * 
     */
    XOF,

    /**
     * PALLAD
     * 
     */
    XPD,

    /**
     * FRANK CFP
     * 
     */
    XPF,

    /**
     * PLATYNA
     * 
     */
    XPT,

    /**
     * SUCRE SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE
     * 
     */
    XSU,

    /**
     * ADB UNIT OF ACCOUNT MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP
     * 
     */
    XUA,

    /**
     * BRAK WALUTY
     * 
     */
    XXX,

    /**
     * RIAL JEMEŃSKI
     * 
     */
    YER,

    /**
     * RAND
     * 
     */
    ZAR,

    /**
     * KWACHA ZAMBIJSKA
     * 
     */
    ZMW,

    /**
     * DOLAR ZIMBABWE
     * 
     */
    ZWL;

    public String value() {
        return name();
    }

    public static TKodWaluty fromValue(String v) {
        return valueOf(v);
    }

}
