//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.03 at 03:53:58 PM TRT 
//


package com.kodat.of.melasoft.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TKodyKrajowUE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TKodyKrajowUE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="AT"/>
 *     &lt;enumeration value="BE"/>
 *     &lt;enumeration value="BG"/>
 *     &lt;enumeration value="CY"/>
 *     &lt;enumeration value="CZ"/>
 *     &lt;enumeration value="DK"/>
 *     &lt;enumeration value="EE"/>
 *     &lt;enumeration value="FI"/>
 *     &lt;enumeration value="FR"/>
 *     &lt;enumeration value="DE"/>
 *     &lt;enumeration value="EL"/>
 *     &lt;enumeration value="HR"/>
 *     &lt;enumeration value="HU"/>
 *     &lt;enumeration value="IE"/>
 *     &lt;enumeration value="IT"/>
 *     &lt;enumeration value="LV"/>
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="LU"/>
 *     &lt;enumeration value="MT"/>
 *     &lt;enumeration value="NL"/>
 *     &lt;enumeration value="PL"/>
 *     &lt;enumeration value="PT"/>
 *     &lt;enumeration value="RO"/>
 *     &lt;enumeration value="SK"/>
 *     &lt;enumeration value="SI"/>
 *     &lt;enumeration value="ES"/>
 *     &lt;enumeration value="SE"/>
 *     &lt;enumeration value="XI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TKodyKrajowUE", namespace = "http://crd.gov.pl/wzor/2023/06/29/12648/")
@XmlEnum
public enum TKodyKrajowUE {


    /**
     * AUSTRIA
     * 
     */
    AT,

    /**
     * BELGIA
     * 
     */
    BE,

    /**
     * BUŁGARIA
     * 
     */
    BG,

    /**
     * CYPR
     * 
     */
    CY,

    /**
     * CZECHY
     * 
     */
    CZ,

    /**
     * DANIA
     * 
     */
    DK,

    /**
     * ESTONIA
     * 
     */
    EE,

    /**
     * FINLANDIA
     * 
     */
    FI,

    /**
     * FRANCJA
     * 
     */
    FR,

    /**
     * NIEMCY
     * 
     */
    DE,

    /**
     * GRECJA
     * 
     */
    EL,

    /**
     * CHORWACJA
     * 
     */
    HR,

    /**
     * WĘGRY
     * 
     */
    HU,

    /**
     * IRLANDIA
     * 
     */
    IE,

    /**
     * WŁOCHY
     * 
     */
    IT,

    /**
     * ŁOTWA
     * 
     */
    LV,

    /**
     * LITWA
     * 
     */
    LT,

    /**
     * LUKSEMBURG
     * 
     */
    LU,

    /**
     * MALTA
     * 
     */
    MT,

    /**
     * HOLANDIA
     * 
     */
    NL,

    /**
     * POLSKA
     * 
     */
    PL,

    /**
     * PORTUGALIA
     * 
     */
    PT,

    /**
     * RUMUNIA
     * 
     */
    RO,

    /**
     * SŁOWACJA
     * 
     */
    SK,

    /**
     * SŁOWENIA
     * 
     */
    SI,

    /**
     * HISZPANIA
     * 
     */
    ES,

    /**
     * SZWECJA
     * 
     */
    SE,

    /**
     * IRLANDIA PÓŁNOCNA
     * 
     */
    XI;

    public String value() {
        return name();
    }

    public static TKodyKrajowUE fromValue(String v) {
        return valueOf(v);
    }

}
