//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.03 at 03:53:58 PM TRT 
//


package com.kodat.of.melasoft.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TOznaczenieProceduryZ.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TOznaczenieProceduryZ">
 *   &lt;restriction base="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy">
 *     &lt;enumeration value="WSTO_EE"/>
 *     &lt;enumeration value="IED"/>
 *     &lt;enumeration value="TT_D"/>
 *     &lt;enumeration value="B_SPV"/>
 *     &lt;enumeration value="B_SPV_DOSTAWA"/>
 *     &lt;enumeration value="B_MPV_PROWIZJA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TOznaczenieProceduryZ", namespace = "http://crd.gov.pl/wzor/2023/06/29/12648/")
@XmlEnum
public enum TOznaczenieProceduryZ {


    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 2a rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    WSTO_EE,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 2b rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    IED,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 5 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    TT_D,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 10 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_SPV,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 11 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_SPV_DOSTAWA,

    /**
     * Oznaczenie dotyczące procedury, o której mowa w § 10 ust. 4 pkt 12 rozporządzenia w sprawie szczegółowego zakresu danych zawartych w deklaracjach podatkowych i w ewidencji w zakresie podatku od towarów i usług
     * 
     */
    B_MPV_PROWIZJA;

    public String value() {
        return name();
    }

    public static TOznaczenieProceduryZ fromValue(String v) {
        return valueOf(v);
    }

}
