//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.03 at 03:53:58 PM TRT 
//


package com.kodat.of.melasoft.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Zestaw danych identyfikacyjnych oraz danych adresowych nabywcy
 * 
 * <p>Java class for TPodmiot2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPodmiot2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="NIP" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TNrNIP"/>
 *           &lt;sequence>
 *             &lt;element name="KodUE" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TKodyKrajowUE"/>
 *             &lt;element name="NrVatUE" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TNrVatUE"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="KodKraju" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TKodKraju" minOccurs="0"/>
 *             &lt;element name="NrID">
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TNrIdentyfikacjiPodatkowej">
 *                   &lt;pattern value="[a-zA-Z0-9]{1,50}"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/element>
 *           &lt;/sequence>
 *           &lt;element name="BrakID" type="{http://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/}TWybor1"/>
 *         &lt;/choice>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="Nazwa" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy512"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPodmiot2", namespace = "http://crd.gov.pl/wzor/2023/06/29/12648/", propOrder = {
    "nip",
    "kodUE",
    "nrVatUE",
    "kodKraju",
    "nrID",
    "brakID",
    "nazwa"
})
public class TPodmiot2 {

    @XmlElement(name = "NIP")
    protected String nip;
    @XmlElement(name = "KodUE")
    @XmlSchemaType(name = "normalizedString")
    protected TKodyKrajowUE kodUE;
    @XmlElement(name = "NrVatUE")
    protected String nrVatUE;
    @XmlElement(name = "KodKraju")
    @XmlSchemaType(name = "normalizedString")
    protected TKodKraju kodKraju;
    @XmlElement(name = "NrID")
    protected String nrID;
    @XmlElement(name = "BrakID")
    protected Byte brakID;
    @XmlElement(name = "Nazwa")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nazwa;

    /**
     * Gets the value of the nip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNIP() {
        return nip;
    }

    /**
     * Sets the value of the nip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNIP(String value) {
        this.nip = value;
    }

    /**
     * Gets the value of the kodUE property.
     * 
     * @return
     *     possible object is
     *     {@link TKodyKrajowUE }
     *     
     */
    public TKodyKrajowUE getKodUE() {
        return kodUE;
    }

    /**
     * Sets the value of the kodUE property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodyKrajowUE }
     *     
     */
    public void setKodUE(TKodyKrajowUE value) {
        this.kodUE = value;
    }

    /**
     * Gets the value of the nrVatUE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrVatUE() {
        return nrVatUE;
    }

    /**
     * Sets the value of the nrVatUE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrVatUE(String value) {
        this.nrVatUE = value;
    }

    /**
     * Gets the value of the kodKraju property.
     * 
     * @return
     *     possible object is
     *     {@link TKodKraju }
     *     
     */
    public TKodKraju getKodKraju() {
        return kodKraju;
    }

    /**
     * Sets the value of the kodKraju property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodKraju }
     *     
     */
    public void setKodKraju(TKodKraju value) {
        this.kodKraju = value;
    }

    /**
     * Gets the value of the nrID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrID() {
        return nrID;
    }

    /**
     * Sets the value of the nrID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrID(String value) {
        this.nrID = value;
    }

    /**
     * Gets the value of the brakID property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getBrakID() {
        return brakID;
    }

    /**
     * Sets the value of the brakID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setBrakID(Byte value) {
        this.brakID = value;
    }

    /**
     * Gets the value of the nazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwa() {
        return nazwa;
    }

    /**
     * Sets the value of the nazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwa(String value) {
        this.nazwa = value;
    }

}
