//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.03 at 03:53:58 PM TRT 
//


package com.kodat.of.melasoft.model;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Informacje o rachunku
 * 
 * <p>Java class for TRachunekBankowy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRachunekBankowy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="NrRB" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TNrRB"/>
 *           &lt;element name="SWIFT" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}SWIFT_Type" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="RachunekWlasnyBanku" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TRachunekWlasnyBanku" minOccurs="0"/>
 *         &lt;element name="NazwaBanku" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy" minOccurs="0"/>
 *         &lt;element name="OpisRachunku" type="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRachunekBankowy", namespace = "http://crd.gov.pl/wzor/2023/06/29/12648/", propOrder = {
    "nrRB",
    "swift",
    "rachunekWlasnyBanku",
    "nazwaBanku",
    "opisRachunku"
})
public class TRachunekBankowy {

    @XmlElement(name = "NrRB", required = true)
    protected String nrRB;
    @XmlElement(name = "SWIFT")
    protected String swift;
    @XmlElement(name = "RachunekWlasnyBanku")
    protected BigInteger rachunekWlasnyBanku;
    @XmlElement(name = "NazwaBanku")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nazwaBanku;
    @XmlElement(name = "OpisRachunku")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String opisRachunku;

    /**
     * Gets the value of the nrRB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrRB() {
        return nrRB;
    }

    /**
     * Sets the value of the nrRB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrRB(String value) {
        this.nrRB = value;
    }

    /**
     * Gets the value of the swift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFT() {
        return swift;
    }

    /**
     * Sets the value of the swift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFT(String value) {
        this.swift = value;
    }

    /**
     * Gets the value of the rachunekWlasnyBanku property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRachunekWlasnyBanku() {
        return rachunekWlasnyBanku;
    }

    /**
     * Sets the value of the rachunekWlasnyBanku property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRachunekWlasnyBanku(BigInteger value) {
        this.rachunekWlasnyBanku = value;
    }

    /**
     * Gets the value of the nazwaBanku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwaBanku() {
        return nazwaBanku;
    }

    /**
     * Sets the value of the nazwaBanku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwaBanku(String value) {
        this.nazwaBanku = value;
    }

    /**
     * Gets the value of the opisRachunku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisRachunku() {
        return opisRachunku;
    }

    /**
     * Sets the value of the opisRachunku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisRachunku(String value) {
        this.opisRachunku = value;
    }

}
