//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.03 at 03:53:58 PM TRT 
//


package com.kodat.of.melasoft.model;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TRodzajFaktury.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TRodzajFaktury">
 *   &lt;restriction base="{http://crd.gov.pl/wzor/2023/06/29/12648/}TZnakowy">
 *     &lt;enumeration value="VAT"/>
 *     &lt;enumeration value="KOR"/>
 *     &lt;enumeration value="ZAL"/>
 *     &lt;enumeration value="ROZ"/>
 *     &lt;enumeration value="UPR"/>
 *     &lt;enumeration value="KOR_ZAL"/>
 *     &lt;enumeration value="KOR_ROZ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TRodzajFaktury", namespace = "http://crd.gov.pl/wzor/2023/06/29/12648/")
@XmlEnum
public enum TRodzajFaktury {


    /**
     * Faktura podstawowa
     * 
     */
    VAT,

    /**
     * Faktura korygująca
     * 
     */
    KOR,

    /**
     * Faktura dokumentująca otrzymanie zapłaty lub jej części przed dokonaniem czynności oraz faktura wystawiona w związku z art. 106f ust. 4 ustawy
     * 
     */
    ZAL,

    /**
     * Faktura wystawiona w związku z art. 106f ust. 3 ustawy
     * 
     */
    ROZ,

    /**
     * Faktura, o której mowa w art. 106e ust. 5 pkt 3 ustawy
     * 
     */
    UPR,

    /**
     * Faktura korygująca fakturę dokumentującą otrzymanie zapłaty lub jej części przed dokonaniem czynności oraz fakturę wystawioną w związku z art. 106f ust. 4 ustawy
     * 
     */
    KOR_ZAL,

    /**
     * Faktura korygująca fakturę wystawioną w związku z art. 106f ust. 3 ustawy
     * 
     */
    KOR_ROZ;

    public String value() {
        return name();
    }

    public static TRodzajFaktury fromValue(String v) {
        return valueOf(v);
    }

}
